### ISSUE TITLE
Add links to actions guide and api docs

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/ember-components#3]
https://guides.emberjs.com/v2.4.0/templates/actions/

http://emberjs.com/api/classes/Ember.ActionHandler.html#method_send

**Comment by gaand** [comment]
I added this in additional resources in 27ed4ee56a5af5db37354e52a74326db9ee499e6.  Not sure if that's what you wanted.

**Comment by jrhorn424** [comment]
Yes, thanks!
